name: Build & Deploy — Dev

on:
  push:
    branches:
      - main

jobs:
  dockr-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven

      - name: Extract Maven project version
        id: pom-version
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> "$GITHUB_OUTPUT"

      - name: Bild tag version
        id: tag-version
        run: echo "version=${{ steps.pom-version.outputs.version }}-${{ github.run_number }}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Maven build
        run: mvn clean install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/Dockerfile.dev
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/zawthanoo/inventory-service:${{ steps.tag-version.outputs.version }}

      - name: Checkout Kustomize chart Repository
        uses: actions/checkout@v3
        with:
          repository: zawthanoo/workshop-apps
          path: deployment
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      # - name: Update image tag in dev overlay
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     repository: zawthanoo/workshop-apps
      #     valueFile: inventory-service/overlays/dev/kustomization.yaml
      #     branch: main
      #     createPR: "false"
      #     message: "inventory-service dev release for workshop"
      #     token: ${{ secrets.MY_GITHUB_TOKEN }}
      #     workDir: deployment
      #     changes: |
      #       {
      #         "images[0].newTag": "${{ steps.tag-version.outputs.version }}"
      #       }
